### ISSUE TITLE
an option to retrieve unseal keys from file

### ISSUE THREAD

**Issue by avoidik** [omegion/vault-unseal#6]
**Is your feature request related to a problem? Please describe.**
A problem with the current implementation is that sensitive unseal keys will be visible in a process list or body of a cronjob, which is not quite secure

**Describe the solution you'd like**
read unseal keys from file

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
`vault operator init` command is able to produce output in json format, technically this file can be stored and read as is (for instance mapped as Kubernetes Secret or ConfigMap object)

**Additional context**
None

**Comment by omegion** [comment]
It's a good idea. We can read the keys from the config file.

**Comment by omegion** [comment]
It is implemented with https://github.com/omegion/vault-unseal/pull/11
