### ISSUE TITLE
make tlsSkipVerify option configurable

### ISSUE THREAD

**Issue by avoidik** [omegion/vault-unseal#7]
**Is your feature request related to a problem? Please describe.**
`tlsSkipVerify` option is hardcoded to `true`

**Describe the solution you'd like**
An option to set Vault HTTPS API certificates

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
Typically the certificates are stored as files, so it would make sense to read these certificates as files (for instance mapped Kubernetes Secret or ConfigMap objects)

**Additional context**
None

**Comment by omegion** [comment]
It is already implemented.
